### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by ca5ua1** [abulimov/lyricstagger#2]
```
$ lyricstagger tag music
Tagging...  [------------------------------------]    0%Exception in thread Thread-3:
Traceback (most recent call last):
  File "/nix/store/pa7ad0v5hs8amap6j09dh72cwc36l0sv-python3-3.11.3/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/lyricstagger/engine.py", line 26, in run
    self.action(self.logger, filepath)
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/lyricstagger/actions.py", line 17, in tag
    lyrics = misc.fetch(data["artist"],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/lyricstagger/misc.py", line 24, in fetch
    lyrics = helper.fetch(artist, song, album)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/lyricstagger/helpers/darklyrics.py", line 245, in fetch
    album_page = self._get_album_page(artist, album)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/lyricstagger/helpers/darklyrics.py", line 227, in _get_album_page
    artist_page = self._get_artist_page(artist)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/lyricstagger/helpers/darklyrics.py", line 206, in _get_artist_page
    artist_link = self.parse_artist_link(search_page)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/lyricstagger/helpers/darklyrics.py", line 117, in parse_artist_link
    soup = BeautifulSoup(data, "html.parser")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/nix/store/pa7ad0v5hs8amap6j09dh72cwc36l0sv-python3-3.11.3/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/lyricstagger/engine.py", line 26, in run
    self.action(self.logger, filepath)
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/lyricstagger/actions.py", line 17, in tag
    lyrics = misc.fetch(data["artist"],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/lyricstagger/misc.py", line 24, in fetch
    lyrics = helper.fetch(artist, song, album)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/lyricstagger/helpers/darklyrics.py", line 245, in fetch
    album_page = self._get_album_page(artist, album)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/lyricstagger/helpers/darklyrics.py", line 227, in _get_album_page
    artist_page = self._get_artist_page(artist)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/lyricstagger/helpers/darklyrics.py", line 206, in _get_artist_page
    artist_link = self.parse_artist_link(search_page)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/lyricstagger/helpers/darklyrics.py", line 117, in parse_artist_link
    soup = BeautifulSoup(data, "html.parser")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/nix/store/pa7ad0v5hs8amap6j09dh72cwc36l0sv-python3-3.11.3/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/lyricstagger/engine.py", line 26, in run
    self.action(self.logger, filepath)
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/lyricstagger/actions.py", line 17, in tag
    lyrics = misc.fetch(data["artist"],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/lyricstagger/misc.py", line 24, in fetch
    lyrics = helper.fetch(artist, song, album)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/lyricstagger/helpers/darklyrics.py", line 245, in fetch
    album_page = self._get_album_page(artist, album)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/lyricstagger/helpers/darklyrics.py", line 227, in _get_album_page
    artist_page = self._get_artist_page(artist)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/lyricstagger/helpers/darklyrics.py", line 206, in _get_artist_page
    artist_link = self.parse_artist_link(search_page)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/lyricstagger/helpers/darklyrics.py", line 117, in parse_artist_link
    soup = BeautifulSoup(data, "html.parser")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/nix/store/pa7ad0v5hs8amap6j09dh72cwc36l0sv-python3-3.11.3/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/lyricstagger/engine.py", line 26, in run
    self.action(self.logger, filepath)
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/lyricstagger/actions.py", line 17, in tag
    lyrics = misc.fetch(data["artist"],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/lyricstagger/misc.py", line 24, in fetch
    lyrics = helper.fetch(artist, song, album)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/lyricstagger/helpers/darklyrics.py", line 245, in fetch
    album_page = self._get_album_page(artist, album)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/lyricstagger/helpers/darklyrics.py", line 227, in _get_album_page
    artist_page = self._get_artist_page(artist)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/lyricstagger/helpers/darklyrics.py", line 206, in _get_artist_page
    artist_link = self.parse_artist_link(search_page)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/lyricstagger/helpers/darklyrics.py", line 117, in parse_artist_link
    soup = BeautifulSoup(data, "html.parser")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/casual/Downloads/venv/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
^C
-----
Processed 4 files, operations summary:
Tags written: 0, Tags removed: 0,
Lyrics missing: 0, Lyrics not saved: 0

Aborted!

```

**Comment by abulimov** [comment]
Thanks for reporting, but this project is now abandoned. I will archive the repo.
